# Generated by Django 4.2.26 on 2025-11-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('auteur', models.CharField(default='Lift and Light', max_length=100, verbose_name='Auteur')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('resume', models.TextField(help_text="Résumé court de l'article (max 500 caractères)", max_length=500, verbose_name='Résumé')),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Image principale')),
                ('date_publication', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('publie', models.BooleanField(default=True, verbose_name='Publié')),
                ('vue', models.IntegerField(default=0, verbose_name='Nombre de vues')),
                ('categories', models.ManyToManyField(blank=True, related_name='articles', to='blog.categoriearticle', verbose_name='Catégories')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-date_publication'],
            },
        ),
    ]
