# Generated by Django 4.2.26 on 2025-11-16 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('categorie', models.CharField(choices=[('ascenseur', 'Ascenseur'), ('climatisation', 'Climatisation'), ('electricite', 'Électricité'), ('groupe_electrogene', 'Groupe Électrogène')], max_length=50)),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='projets/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ImageProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projets/galeries/')),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('ordre', models.IntegerField(default=0)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projets.projet')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['ordre', 'date_ajout'],
            },
        ),
    ]
